# Generated by Django 4.2.7 on 2023-12-10 16:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orderInput", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="item",
            old_name="category_id",
            new_name="category",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="customer_id",
            new_name="customer",
        ),
        migrations.AddField(
            model_name="order",
            name="items",
            field=models.ManyToManyField(to="orderInput.item"),
        ),
        migrations.DeleteModel(
            name="OrderItem",
        ),
    ]
