# Generated by Django 4.2.7 on 2023-12-10 16:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orderInput", "0002_rename_category_id_item_category_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="line_number",
        ),
        migrations.RemoveField(
            model_name="order",
            name="page_number",
        ),
        migrations.AddField(
            model_name="item",
            name="line_number",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="item",
            name="page_number",
            field=models.IntegerField(default=0),
        ),
    ]
