# Generated by Django 4.2.7 on 2023-12-10 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "orderInput",
            "0003_remove_order_line_number_remove_order_page_number_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="customer",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="orderInput.customer"
            ),
        ),
    ]
