# Generated by Django 4.2.7 on 2023-12-10 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("orderInput", "0005_remove_order_items_item_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="orderInput.order"
            ),
        ),
    ]
