# Generated by Django 4.2.7 on 2023-12-10 17:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orderInput", "0007_alter_order_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 12, 10, 17, 21, 11, 443296, tzinfo=datetime.timezone.utc
                ),
                verbose_name="date created",
            ),
        ),
    ]
