# Generated by Django 4.2.7 on 2023-12-10 18:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orderInput", "0009_alter_order_created"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="quantity",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="order",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 12, 10, 18, 11, 48, 958626, tzinfo=datetime.timezone.utc
                ),
                verbose_name="date created",
            ),
        ),
    ]
