# Generated by Django 4.2.7 on 2023-12-10 18:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orderInput", "0011_order_items_alter_order_created"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="items",
        ),
        migrations.AlterField(
            model_name="order",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 12, 10, 18, 14, 31, 830527, tzinfo=datetime.timezone.utc
                ),
                verbose_name="date created",
            ),
        ),
    ]
