# Generated by Django 4.2.7 on 2023-12-10 20:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orderInput", "0012_remove_order_items_alter_order_created"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="grade",
            field=models.CharField(
                choices=[
                    ("choice", "Choice"),
                    ("prime", "Prime"),
                    ("american", "American"),
                    ("australian", "Australian"),
                    ("new_zealand", "New Zealand"),
                    ("amish", "Amish"),
                    ("berkshire", "Berkshire"),
                ],
                default="default",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="type",
            field=models.CharField(
                choices=[
                    ("whole_in_the_bag", "Whole in the Bag"),
                    ("whole_trimmed_and_tied", "Whole Trimmed and Tied"),
                    ("center_cut", "Center Cut"),
                    ("bone_in_quantity", "Bone-in Quantity"),
                    ("bone_less_quantity", "Bone-less Quantity"),
                    ("racks", "Racks"),
                    ("loins", "Loins"),
                    ("rib_chops", "Rib Chops"),
                    ("legs", "Legs"),
                ],
                default="default",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="category",
            field=models.CharField(
                choices=[
                    ("tenderloin", "Tenderloin"),
                    ("rib_roast", "Rib Roast"),
                    ("steaks", "Steaks"),
                    ("lamb", "Lamb"),
                    ("ham", "Ham"),
                    ("misc", "Miscellaneous"),
                ],
                default="default",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 12, 10, 20, 36, 32, 773243, tzinfo=datetime.timezone.utc
                ),
                verbose_name="date created",
            ),
        ),
        migrations.DeleteModel(
            name="Category",
        ),
    ]
