# Generated by Django 4.2.7 on 2023-12-10 20:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orderInput", "0013_item_grade_item_type_alter_item_category_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="type",
        ),
        migrations.AddField(
            model_name="item",
            name="item_type",
            field=models.CharField(
                choices=[
                    ("amish", "Amish"),
                    ("berkshire", "Berkshire"),
                    ("bone_in_quantity", "Bone-in Quantity"),
                    ("bone_less_quantity", "Bone-less Quantity"),
                    ("racks", "Racks"),
                    ("loins", "Loins"),
                    ("rib_chops", "Rib Chops"),
                    ("legs", "Legs"),
                    ("whole_in_the_bag", "Whole in the Bag"),
                    ("whole_trimmed_and_tied", "Whole Trimmed and Tied"),
                    ("center_cut", "Center Cut"),
                ],
                default="default",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="grade",
            field=models.CharField(
                choices=[
                    ("choice", "Choice"),
                    ("prime", "Prime"),
                    ("american", "American"),
                    ("australian", "Australian"),
                    ("new_zealand", "New Zealand"),
                ],
                default="default",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 12, 10, 20, 58, 27, 645632, tzinfo=datetime.timezone.utc
                ),
                verbose_name="date created",
            ),
        ),
    ]
